version: "3.9"

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${MYSQL_DATABASE:-zerion}
      MYSQL_USER: ${MYSQL_USER:-zerion}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-zerion}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  server:
    build: ./server
    env_file:
      - .env
    depends_on:
      - redis
      - mysql
    ports:
      - "8000:8000"

  client:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - NEXT_TELEMETRY_DISABLED=1
    depends_on:
      - server

  nginx:
    image: nginx:alpine
    depends_on:
      - client
      - server
    ports:
      - "8080:80"
    volumes:
      - ./ops/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  mysql_data:
  redis_data:



